<?php

namespace Ibex\CrudGenerator;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\File;
use Illuminate\Console\Concerns\InteractsWithIO;
use Symfony\Component\Console\Output\ConsoleOutput;


class RouteGenerator
{
    use InteractsWithIO;


    protected string $routesPath;
    protected string $modelName;
    protected string $stack;
    protected bool $isDryRun;
    protected string $moduleName;


    public function __construct(?string $modelName = null, ?string $stack = null, bool $isDryRun = false, ?string $moduleName = null)
    {

        $this->output = new ConsoleOutput();


        $this->modelName = $modelName;
        $this->stack = $stack;
        $this->isDryRun = $isDryRun;
        $this->moduleName = $moduleName;

        $basePath = $isDryRun ? base_path('DryRun') : base_path();

        if ($moduleName) {
            $this->routesPath = $basePath . "/Modules/{$moduleName}/Routes/" . ($stack === 'api' ? 'api.php' : 'web.php');
        } else {
            $this->routesPath = $basePath . '/routes/' . ($stack === 'api' ? 'api.php' : 'web.php');
        }
    }

    public function generate(): void
    {
        if ($this->isDryRun) {
            // Create dry-run routes directory
            $routeDir = dirname($this->routesPath);
            if (!File::exists($routeDir)) {
                File::makeDirectory($routeDir, 0755, true);
            }

            // Copy existing route file to dry-run directory
            if (!File::exists($this->routesPath)) {
                File::copy(
                    $this->stack === 'api' ? base_path('routes/api.php') : base_path('routes/web.php'),
                    $this->routesPath
                );
            }
        }

        $routeContent = File::get($this->routesPath);
        // $this->info("Came here...1");
        $newRoutes = $this->getRouteDefinition();
        // $this->info("Came here...2");
        if (Str::contains($routeContent, $this->getRouteSignature())) {
            $routeContent = $this->commentExistingRoutes($routeContent);
        }

        // $this->info("Route Path...".$this->routesPath);
        // $this->info("Came here to write route...".$routeContent . "\n" . $newRoutes);
        File::put($this->routesPath, $routeContent . "\n" . $newRoutes);
        // $this->info("Route Written...");
    }

    protected function getRouteDefinition(): string
    {
        $modelName = Str::kebab($this->modelName);
        $controllerName = "{$this->modelName}Controller";
        $moduleNamespace = $this->moduleName ? "Modules\\{$this->moduleName}\\" : "App\\";



        if ($this->isDryRun) {
            $moduleNamespace = $this->moduleName ? "DryRun\\Modules\\{$this->moduleName}\\" : "App\\";
        }

        if ($this->stack === 'livewire') {
            return "
            // Generated by Ibex\CrudGenerator - " . date('Y-m-d H:i:s') . "
            Route::get('/{$modelName}', \\{$moduleNamespace}Livewire\\{$this->modelName}s\Index::class)->name('{$modelName}.index');
            Route::get('/{$modelName}/create', \\{$moduleNamespace}Livewire\\{$this->modelName}s\Create::class)->name('{$modelName}.create');
            Route::get('/{$modelName}/show/{model}', \\{$moduleNamespace}Livewire\\{$this->modelName}s\Show::class)->name('{$modelName}.show');
            Route::get('/{$modelName}/update/{model}', \\{$moduleNamespace}Livewire\\{$this->modelName}s\Edit::class)->name('{$modelName}.edit');";
        }

        if ($this->stack === 'api') {
            return "
            // Generated by Ibex\CrudGenerator - " . date('Y-m-d H:i:s') . "
            Route::apiResource('{$modelName}', \\{$moduleNamespace}Http\Controllers\Api\\{$controllerName}::class);";
        }

        return "
        // Generated by Ibex\CrudGenerator - " . date('Y-m-d H:i:s') . "\n".
        "use {$moduleNamespace}Http\Controllers\\{$controllerName};". "\n".
        "Route::middleware(['auth', 'verified'])->group(function () {
            Route::resource('{$modelName}', {$controllerName}::class)->names('{$modelName}');
        });";"
        // Route::resource('{$modelName}', \\{$moduleNamespace}Http\Controllers\\{$controllerName}::class);";
    }

    protected function getRouteSignature(): string
    {
        $modelName = Str::kebab($this->modelName);
        return $this->stack === 'api'
            ? "Route::apiResource('{$modelName}'"
            : "Route::resource('{$modelName}'";
    }

    protected function commentExistingRoutes(string $content): string
    {
        $lines = explode("\n", $content);
        $inRouteBlock = false;

        foreach ($lines as &$line) {
            if (Str::contains($line, $this->getRouteSignature())) {
                $inRouteBlock = true;
                $line = "// " . $line . " // Commented by Ibex\CrudGenerator - " . date('Y-m-d H:i:s');
            } elseif ($inRouteBlock && Str::contains($line, '});')) {
                $inRouteBlock = false;
                $line = "// " . $line;
            } elseif ($inRouteBlock) {
                $line = "// " . $line;
            }
        }

        return implode("\n", $lines);
    }
}
