<?php

namespace Ibex\CrudGenerator;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\File;

class RouteGenerator
{
    protected string $routesPath;
    protected string $modelName;
    protected string $stack;
    protected bool $isDryRun;
    protected string $moduleName;


    public function __construct(string $modelName, string $stack, bool $isDryRun = false, ?string $moduleName = null)
    {
        $this->modelName = $modelName;
        $this->stack = $stack;
        $this->isDryRun = $isDryRun;
        $this->moduleName = $moduleName;

        if ($moduleName) {
            $this->routesPath = base_path("Modules/{$moduleName}/Routes/" . ($stack === 'api' ? 'api.php' : 'web.php'));
        } else {
            $this->routesPath = $stack === 'api' ? base_path('routes/api.php') : base_path('routes/web.php');
        }

        // $this->routesPath = $stack === 'api' ? base_path('routes/api.php') : base_path('routes/web.php');
        if ($this->isDryRun) {
            $dryRunBase = base_path('DryRun');
            $this->routesPath = $dryRunBase . ($moduleName ? "/Modules/{$moduleName}/Routes/" : '/routes/') . ($stack === 'api' ? 'api.php' : 'web.php');
        }
    }

    public function generate(): void
    {
        if ($this->isDryRun) {
            // Create dry-run routes directory
            $routeDir = dirname($this->routesPath);
            if (!File::exists($routeDir)) {
                File::makeDirectory($routeDir, 0755, true);
            }

            // Copy existing route file to dry-run directory
            if (!File::exists($this->routesPath)) {
                File::copy(
                    $this->stack === 'api' ? base_path('routes/api.php') : base_path('routes/web.php'),
                    $this->routesPath
                );
            }
        }

        $routeContent = File::get($this->routesPath);
        $newRoutes = $this->getRouteDefinition();

        if (Str::contains($routeContent, $this->getRouteSignature())) {
            $routeContent = $this->commentExistingRoutes($routeContent);
        }

        File::put($this->routesPath, $routeContent . "\n" . $newRoutes);
    }

    protected function getRouteDefinition(): string
    {
        $modelName = Str::kebab($this->modelName);
        $controllerName = "{$this->modelName}Controller";
        $moduleNamespace = $this->moduleName ? "Modules\\{$this->moduleName}\\" : "App\\";

        if ($this->stack === 'livewire') {
            return "
            // Generated by Ibex\CrudGenerator - " . date('Y-m-d H:i:s') . "
            Route::get('/{$modelName}', \\{$moduleNamespace}Livewire\\{$this->modelName}s\Index::class)->name('{$modelName}.index');
            Route::get('/{$modelName}/create', \\{$moduleNamespace}Livewire\\{$this->modelName}s\Create::class)->name('{$modelName}.create');
            Route::get('/{$modelName}/show/{model}', \\{$moduleNamespace}Livewire\\{$this->modelName}s\Show::class)->name('{$modelName}.show');
            Route::get('/{$modelName}/update/{model}', \\{$moduleNamespace}Livewire\\{$this->modelName}s\Edit::class)->name('{$modelName}.edit');";
        }

        if ($this->stack === 'api') {
            return "
            // Generated by Ibex\CrudGenerator - " . date('Y-m-d H:i:s') . "
            Route::apiResource('{$modelName}', \\{$moduleNamespace}Http\Controllers\Api\\{$controllerName}::class);";
        }

        return "
        // Generated by Ibex\CrudGenerator - " . date('Y-m-d H:i:s') . "
        Route::resource('{$modelName}', \\{$moduleNamespace}Http\Controllers\\{$controllerName}::class);";
    }

    protected function getRouteSignature(): string
    {
        $modelName = Str::kebab($this->modelName);
        return $this->stack === 'api'
            ? "Route::apiResource('{$modelName}'"
            : "Route::resource('{$modelName}'";
    }

    protected function commentExistingRoutes(string $content): string
    {
        $lines = explode("\n", $content);
        $inRouteBlock = false;

        foreach ($lines as &$line) {
            if (Str::contains($line, $this->getRouteSignature())) {
                $inRouteBlock = true;
                $line = "// " . $line . " // Commented by Swat\Swatcode - " . date('Y-m-d H:i:s');
            } elseif ($inRouteBlock && Str::contains($line, '});')) {
                $inRouteBlock = false;
                $line = "// " . $line;
            } elseif ($inRouteBlock) {
                $line = "// " . $line;
            }
        }

        return implode("\n", $lines);
    }
}
